# ------------------------------ #
#       Pembuat Proyek           #
#   > Ludang prasetyo .N         #
#   > Teknik Komputer S1         #
#   > 225510017                  #
#                                #
# ------------------------------ #
name:  Ludang_Proyek_UAS_Pemrograman_Mobile  
# ------------------
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
  # ------------- !! Databes MySql !! ------------- #
  # dependencies:
  # flutter:
  #   sdk: flutter
  # mysql1: ^0.23.0
  # ------------- !! Databes MySql !! ------------- #
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
# ---------------------
  # flutter_radar: ^3.9.1
  # flutter_map: ^0.14.2
  # latlong: ^1.0.2
# --------------------
  image_picker: ^0.8.4+4
dev_dependencies:
  flutter_test:
    sdk: flutter
# --------------------
flutter:
  uses-material-design: true
  assets:
    # --------------  Foto yang di simpan di assets  -------------- # 
    - assets/rohmat.jpg
    - assets/ludang.jpg
    - assets/fadrian.jpg
    - assets/yoga.jpg
    - assets/riski.jpg
    - assets/trio.jpg
    - assets/utdi.jpg
    # --------------  Bila semua folder data di assets  -------------- # 
    # - assets/locations/ludang.dart
    # - assets/locations/fadrian.dart
    # - assets/locations/rohmat.dart
    # - assets/locations/yoga.dart
    # - assets/locations/riski.dart
    # - assets/locations/trio.dart
    # - assets/locations/utdi.dart

# ----------------------------
# %YAML 1.1
# ---
# # ludang.customer
# -
#   id_customer: 1
#   nama: "ludang"
# -
#   id_customer: 2
#   nama: "nugroho"
# -
#   id_customer: 356
#   nama: "ghfghf"
# # ludang.orders
# -
#   id_order: 1
#   jumlah: 10
#   id_customer: 1
# -
#   id_order: 2
#   jumlah: 23
#   id_customer: 2
# # phpmyadmin.pma__designer_settings
# -
#   username: "root"
#   settings_data: "{\"angular_direct\":\"direct\",\"snap_to_grid\":\"off\",\"relation_lines\":\"true\"}"
# # phpmyadmin.pma__recent
# -
#   username: "root"
#   tables: "[{\"db\":\"ludang\",\"table\":\"customer\"},{\"db\":\"ludang\",\"table\":\"orders\"},{\"db\":\"mysql\",\"table\":\"help_keyword\"},{\"db\":\"mysql\",\"table\":\"help_category\"},{\"db\":\"mysql\",\"table\":\"gtid_slave_pos\"},{\"db\":\"mysql\",\"table\":\"general_log\"},{\"db\":\"mysql\",\"table\":\"help_topic\"},{\"db\":\"mysql\",\"table\":\"slow_log\"},{\"db\":\"mysql\",\"table\":\"tables_priv\"},{\"db\":\"mysql\",\"table\":\"table_stats\"}]"
# # phpmyadmin.pma__userconfig
# -
#   username: "root"
#   timevalue: "2024-06-26 14:53:44"
#   config_data: "{\"Console\\/Mode\":\"collapse\",\"lang\":\"id\"}"
# ...
